INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Абхазия","Abkhazia","AB","ABH","895");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Австралия","Australia","AU","AUS","036");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Австрия","Austria","AT","AUT","040");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Азербайджан","Azerbaijan","AZ","AZE","031");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Албания","Albania","AL","ALB","008");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Алжир","Algeria","DZ","DZA","012");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Американское Самоа","American Samoa","AS","ASM","016");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ангилья","Anguilla","AI","AIA","660");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ангола","Angola","AO","AGO","024");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Андорра","Andorra","AD","AND","020");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Антарктида","Antarctica","AQ","ATA","010");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Антигуа и Барбуда","Antigua and Barbuda","AG","ATG","028");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Аргентина","Argentina","AR","ARG","032");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Армения","Armenia","AM","ARM","051");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Аруба","Aruba","AW","ABW","533");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Афганистан","Afghanistan","AF","AFG","004");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Багамы","Bahamas","BS","BHS","044");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бангладеш","Bangladesh","BD","BGD","050");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Барбадос","Barbados","BB","BRB","052");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бахрейн","Bahrain","BH","BHR","048");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Беларусь","Belarus","BY","BLR","112");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Белиз","Belize","BZ","BLZ","084");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бельгия","Belgium","BE","BEL","056");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бенин","Benin","BJ","BEN","204");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бермуды","Bermuda","BM","BMU","060");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Болгария","Bulgaria","BG","BGR","100");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Боливия, Многонациональное Государство","Bolivia, plurinational state of","BO","BOL","068");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бонайре, Саба и Синт-Эстатиус","Bonaire, Sint Eustatius and Saba","BQ","BES","535");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Босния и Герцеговина","Bosnia and Herzegovina","BA","BIH","070");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ботсвана","Botswana","BW","BWA","072");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бразилия","Brazil","BR","BRA","076");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Британская территория в Индийском океане","British Indian Ocean Territory","IO","IOT","086");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бруней-Даруссалам","Brunei Darussalam","BN","BRN","096");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Буркина-Фасо","Burkina Faso","BF","BFA","854");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бурунди","Burundi","BI","BDI","108");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Бутан","Bhutan","BT","BTN","064");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Вануату","Vanuatu","VU","VUT","548");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Венгрия","Hungary","HU","HUN","348");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Венесуэла Боливарианская Республика","Venezuela","VE","VEN","862");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Виргинские острова, Британские","Virgin Islands, British","VG","VGB","092");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Виргинские острова, США","Virgin Islands, U.S.","VI","VIR","850");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Вьетнам","Vietnam","VN","VNM","704");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Габон","Gabon","GA","GAB","266");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гаити","Haiti","HT","HTI","332");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гайана","Guyana","GY","GUY","328");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гамбия","Gambia","GM","GMB","270");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гана","Ghana","GH","GHA","288");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гваделупа","Guadeloupe","GP","GLP","312");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гватемала","Guatemala","GT","GTM","320");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гвинея","Guinea","GN","GIN","324");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гвинея-Бисау","Guinea-Bissau","GW","GNB","624");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Германия","Germany","DE","DEU","276");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гернси","Guernsey","GG","GGY","831");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гибралтар","Gibraltar","GI","GIB","292");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гондурас","Honduras","HN","HND","340");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гонконг","Hong Kong","HK","HKG","344");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гренада","Grenada","GD","GRD","308");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гренландия","Greenland","GL","GRL","304");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Греция","Greece","GR","GRC","300");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Грузия","Georgia","GE","GEO","268");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Гуам","Guam","GU","GUM","316");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Дания","Denmark","DK","DNK","208");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Джерси","Jersey","JE","JEY","832");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Джибути","Djibouti","DJ","DJI","262");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Доминика","Dominica","DM","DMA","212");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Доминиканская Республика","Dominican Republic","DO","DOM","214");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Египет","Egypt","EG","EGY","818");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Замбия","Zambia","ZM","ZMB","894");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Западная Сахара","Western Sahara","EH","ESH","732");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Зимбабве","Zimbabwe","ZW","ZWE","716");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Израиль","Israel","IL","ISR","376");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Индия","India","IN","IND","356");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Индонезия","Indonesia","ID","IDN","360");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Иордания","Jordan","JO","JOR","400");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ирак","Iraq","IQ","IRQ","368");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Иран, Исламская Республика","Iran, Islamic Republic of","IR","IRN","364");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ирландия","Ireland","IE","IRL","372");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Исландия","Iceland","IS","ISL","352");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Испания","Spain","ES","ESP","724");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Италия","Italy","IT","ITA","380");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Йемен","Yemen","YE","YEM","887");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кабо-Верде","Cape Verde","CV","CPV","132");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Казахстан","Kazakhstan","KZ","KAZ","398");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Камбоджа","Cambodia","KH","KHM","116");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Камерун","Cameroon","CM","CMR","120");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Канада","Canada","CA","CAN","124");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Катар","Qatar","QA","QAT","634");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кения","Kenya","KE","KEN","404");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кипр","Cyprus","CY","CYP","196");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Киргизия","Kyrgyzstan","KG","KGZ","417");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кирибати","Kiribati","KI","KIR","296");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Китай","China","CN","CHN","156");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кокосовые (Килинг) острова","Cocos (Keeling) Islands","CC","CCK","166");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Колумбия","Colombia","CO","COL","170");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Коморы","Comoros","KM","COM","174");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Конго","Congo","CG","COG","178");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Конго, Демократическая Республика","Congo, Democratic Republic of the","CD","COD","180");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Корея, Народно-Демократическая Республика","Korea, Democratic People's republic of","KP","PRK","408");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Корея, Республика","Korea, Republic of","KR","KOR","410");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Коста-Рика","Costa Rica","CR","CRI","188");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кот д'Ивуар","Cote d'Ivoire","CI","CIV","384");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Куба","Cuba","CU","CUB","192");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кувейт","Kuwait","KW","KWT","414");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Кюрасао","Curaçao","CW","CUW","531");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Лаос","Lao People's Democratic Republic","LA","LAO","418");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Латвия","Latvia","LV","LVA","428");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Лесото","Lesotho","LS","LSO","426");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ливан","Lebanon","LB","LBN","422");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ливийская Арабская Джамахирия","Libyan Arab Jamahiriya","LY","LBY","434");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Либерия","Liberia","LR","LBR","430");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Лихтенштейн","Liechtenstein","LI","LIE","438");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Литва","Lithuania","LT","LTU","440");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Люксембург","Luxembourg","LU","LUX","442");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Маврикий","Mauritius","MU","MUS","480");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мавритания","Mauritania","MR","MRT","478");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мадагаскар","Madagascar","MG","MDG","450");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Майотта","Mayotte","YT","MYT","175");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Макао","Macao","MO","MAC","446");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Малави","Malawi","MW","MWI","454");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Малайзия","Malaysia","MY","MYS","458");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мали","Mali","ML","MLI","466");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Малые Тихоокеанские отдаленные острова Соединенных Штатов","United States Minor Outlying Islands","UM","UMI","581");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мальдивы","Maldives","MV","MDV","462");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мальта","Malta","MT","MLT","470");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Марокко","Morocco","MA","MAR","504");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мартиника","Martinique","MQ","MTQ","474");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Маршалловы острова","Marshall Islands","MH","MHL","584");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мексика","Mexico","MX","MEX","484");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Микронезия, Федеративные Штаты","Micronesia, Federated States of","FM","FSM","583");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мозамбик","Mozambique","MZ","MOZ","508");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Молдова, Республика","Moldova","MD","MDA","498");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Монако","Monaco","MC","MCO","492");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Монголия","Mongolia","MN","MNG","496");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Монтсеррат","Montserrat","MS","MSR","500");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Мьянма","Burma","MM","MMR","104");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Намибия","Namibia","NA","NAM","516");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Науру","Nauru","NR","NRU","520");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Непал","Nepal","NP","NPL","524");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Нигер","Niger","NE","NER","562");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Нигерия","Nigeria","NG","NGA","566");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Нидерланды","Netherlands","NL","NLD","528");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Никарагуа","Nicaragua","NI","NIC","558");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ниуэ","Niue","NU","NIU","570");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Новая Зеландия","New Zealand","NZ","NZL","554");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Новая Каледония","New Caledonia","NC","NCL","540");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Норвегия","Norway","NO","NOR","578");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Объединенные Арабские Эмираты","United Arab Emirates","AE","ARE","784");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Оман","Oman","OM","OMN","512");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Остров Буве","Bouvet Island","BV","BVT","074");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Остров Мэн","Isle of Man","IM","IMN","833");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Остров Норфолк","Norfolk Island","NF","NFK","574");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Остров Рождества","Christmas Island","CX","CXR","162");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Остров Херд и острова Макдональд","Heard Island and McDonald Islands","HM","HMD","334");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Острова Кайман","Cayman Islands","KY","CYM","136");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Острова Кука","Cook Islands","CK","COK","184");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Острова Теркс и Кайкос","Turks and Caicos Islands","TC","TCA","796");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Пакистан","Pakistan","PK","PAK","586");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Палау","Palau","PW","PLW","585");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Палестинская территория, оккупированная","Palestinian Territory, Occupied","PS","PSE","275");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Панама","Panama","PA","PAN","591");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Папский Престол (Государство - город Ватикан)","Holy See (Vatican City State)","VA","VAT","336");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Папуа-Новая Гвинея","Papua New Guinea","PG","PNG","598");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Парагвай","Paraguay","PY","PRY","600");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Перу","Peru","PE","PER","604");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Питкерн","Pitcairn","PN","PCN","612");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Польша","Poland","PL","POL","616");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Португалия","Portugal","PT","PRT","620");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Пуэрто-Рико","Puerto Rico","PR","PRI","630");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Республика Македония","Macedonia, The Former Yugoslav Republic Of","MK","MKD","807");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Реюньон","Reunion","RE","REU","638");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Россия","Russia","RU","RUS","643");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Руанда","Rwanda","RW","RWA","646");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Румыния","Romania","RO","ROU","642");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Самоа","Samoa","WS","WSM","882");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сан-Марино","San Marino","SM","SMR","674");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сан-Томе и Принсипи","Sao Tome and Principe","ST","STP","678");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Саудовская Аравия","Saudi Arabia","SA","SAU","682");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Свазиленд","Swaziland","SZ","SWZ","748");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Святая Елена, Остров вознесения, Тристан-да-Кунья","Saint Helena, Ascension And Tristan Da Cunha","SH","SHN","654");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Северные Марианские острова","Northern Mariana Islands","MP","MNP","580");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сен-Бартельми","Saint Barthélemy","BL","BLM","652");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сен-Мартен","Saint Martin (French Part)","MF","MAF","663");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сенегал","Senegal","SN","SEN","686");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сент-Винсент и Гренадины","Saint Vincent and the Grenadines","VC","VCT","670");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сент-Китс и Невис","Saint Kitts and Nevis","KN","KNA","659");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сент-Люсия","Saint Lucia","LC","LCA","662");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сент-Пьер и Микелон","Saint Pierre and Miquelon","PM","SPM","666");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сербия","Serbia","RS","SRB","688");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сейшелы","Seychelles","SC","SYC","690");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сингапур","Singapore","SG","SGP","702");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Синт-Мартен","Sint Maarten","SX","SXM","534");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сирийская Арабская Республика","Syrian Arab Republic","SY","SYR","760");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Словакия","Slovakia","SK","SVK","703");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Словения","Slovenia","SI","SVN","705");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Соединенное Королевство","United Kingdom","GB","GBR","826");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Соединенные Штаты","United States","US","USA","840");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Соломоновы острова","Solomon Islands","SB","SLB","090");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сомали","Somalia","SO","SOM","706");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Судан","Sudan","SD","SDN","736");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Суринам","Surit_name","SR","SUR","740");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Сьерра-Леоне","Sierra Leone","SL","SLE","694");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Таджикистан","Tajikistan","TJ","TJK","762");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Таиланд","Thailand","TH","THA","764");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Тайвань (Китай)","Taiwan, Province of China","TW","TWN","158");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Танзания, Объединенная Республика","Tanzania, United Republic Of","TZ","TZA","834");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Тимор-Лесте","Timor-Leste","TL","TLS","626");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Того","Togo","TG","TGO","768");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Токелау","Tokelau","TK","TKL","772");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Тонга","Tonga","TO","TON","776");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Тринидад и Тобаго","Trinidad and Tobago","TT","TTO","780");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Тувалу","Tuvalu","TV","TUV","798");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Тунис","Tunisia","TN","TUN","788");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Туркмения","Turkmenistan","TM","TKM","795");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Турция","Turkey","TR","TUR","792");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Уганда","Uganda","UG","UGA","800");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Узбекистан","Uzbekistan","UZ","UZB","860");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Украина","Ukraine","UA","UKR","804");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Уоллис и Футуна","Wallis and Futuna","WF","WLF","876");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Уругвай","Uruguay","UY","URY","858");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Фарерские острова","Faroe Islands","FO","FRO","234");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Фиджи","Fiji","FJ","FJI","242");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Филиппины","Philippines","PH","PHL","608");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Финляндия","Finland","FI","FIN","246");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Фолклендские острова (Мальвинские)","Falkland Islands (Malvinas)","FK","FLK","238");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Франция","France","FR","FRA","250");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Французская Гвиана","French Guiana","GF","GUF","254");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Французская Полинезия","French Polynesia","PF","PYF","258");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Французские Южные территории","French Southern Territories","TF","ATF","260");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Хорватия","Croatia","HR","HRV","191");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Центрально-Африканская Республика","Central African Republic","CF","CAF","140");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Чад","Chad","TD","TCD","148");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Черногория","Montenegro","ME","MNE","499");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Чешская Республика","Czech Republic","CZ","CZE","203");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Чили","Chile","CL","CHL","152");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Швейцария","Switzerland","CH","CHE","756");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Швеция","Sweden","SE","SWE","752");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Шпицберген и Ян Майен","Svalbard and Jan Mayen","SJ","SJM","744");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Шри-Ланка","Sri Lanka","LK","LKA","144");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Эквадор","Ecuador","EC","ECU","218");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Экваториальная Гвинея","Equatorial Guinea","GQ","GNQ","226");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Эландские острова","Åland Islands","AX","ALA","248");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Эль-Сальвадор","El Salvador","SV","SLV","222");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Эритрея","Eritrea","ER","ERI","232");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Эстония","Estonia","EE","EST","233");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Эфиопия","Ethiopia","ET","ETH","231");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Южная Африка","South Africa","ZA","ZAF","710");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Южная Джорджия и Южные Сандвичевы острова","South Georgia and the South Sandwich Islands","GS","SGS","239");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Южная Осетия","South Ossetia","OS","OST","896");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Южный Судан","South Sudan","SS","SSD","728");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Ямайка","Jamaica","JM","JAM","388");
INSERT INTO address_countries(t_name,name,alpha2,alpha3,iso) VALUES("Япония","Japan","JP","JPN","392");
INSERT INTO address_types (name) VALUES('country');
INSERT INTO address_types (name) VALUES('region');
INSERT INTO address_types (name) VALUES('area');
INSERT INTO address_types (name) VALUES('city');
INSERT INTO address_types (name) VALUES('locality');
INSERT INTO address_types (name) VALUES('district');
INSERT INTO address_types (name) VALUES('street');
INSERT INTO address_types (name) VALUES('house');
INSERT INTO address_types (name) VALUES('building');
INSERT INTO address_types (name) VALUES('apartment');