DROP TABLE IF EXISTS `file_links`;
DROP TABLE IF EXISTS `files`;
DROP TABLE IF EXISTS `roles_in_files`;
DROP PROCEDURE IF EXISTS getFileNameById;
DROP PROCEDURE IF EXISTS deleteLinkByFileId;
DROP PROCEDURE IF EXISTS deleteFile;
DROP PROCEDURE IF EXISTS getFileOwner;
DROP PROCEDURE IF EXISTS createFile;
DROP PROCEDURE IF EXISTS getFileRoles;
DROP PROCEDURE IF EXISTS deleteFileRoles;
DROP PROCEDURE IF EXISTS createFileRoles;
DROP PROCEDURE IF EXISTS getFileIdByLink;
DROP PROCEDURE IF EXISTS generateFileLink;
DROP PROCEDURE IF EXISTS checkFileLink;


